
INSERT INTO main.equipment ("Id", "Name", "Type", "Brand", "Model", "Condition", "IdRehearsalPoint") VALUES
('1', 'Combo Amplifier', 'Amplifier', 'Fender', 'Champion 100', 'New', '53'),
('2', 'Combo Amplifier', 'Amplifier', 'Fender', 'Champion 100', 'New', '53'),
('3', 'Combo Amplifier', 'Amplifier', 'Marshall', 'MG30GFX', 'Used', '53'),
('4', 'Drum Kit', 'Drum Set', 'Pearl', 'Export Series', 'Used', '53'),
('5', 'Drum Kit', 'Drum Set', 'Tama', 'Starclassic', 'New', '53'),
('6', 'Synthesizer', 'Synthesizer', 'Yamaha', 'MX61', 'New', '53'),
('7', 'Bass Rental', 'Instrument', 'Fender', 'Precision Bass', 'New', '53'),
('8', 'Combo Amplifier', 'Amplifier', 'Roland', 'CUBE-40GX', 'New', '54'),
('9', 'Combo Amplifier', 'Amplifier', 'Orange', 'Crush Pro', 'Used', '54'),
('10', 'Drum Kit', 'Drum Set', 'Yamaha', 'Stage Custom', 'New', '54'),
('11', 'Combo Amplifier', 'Amplifier', 'Fender', 'Champion 100', 'New', '55'),
('12', 'Microphone', 'Microphone', 'Shure', 'SM58', 'New', '56'),
('13', 'Synthesizer', 'Synthesizer', 'Korg', 'Minilogue', 'Used', '57'),
('14', 'Guitar Amplifier', 'Amplifier', 'Ampeg', 'BA-110', 'New', '58'),
('15', 'Drum Kit', 'Drum Set', 'Mapex', 'Mars Series', 'Used', '59'),
('16', 'Keyboard', 'Synthesizer', 'Roland', 'Juno-DS', 'New', '60'),
('17', 'Bass Guitar', 'Instrument', 'Ibanez', 'SR300E', 'New', '61'),
('18', 'Microphone', 'Microphone', 'Audio-Technica', 'AT2020', 'New', '62'),
('19', 'Combo Amplifier', 'Amplifier', 'Vox', 'VT20X', 'Used', '63'),
('20', 'Drum Kit', 'Drum Set', 'Gretsch', 'Catalina Maple', 'New', '64'),
('21', 'Synthesizer', 'Synthesizer', 'Moog', 'Subsequent 25', 'New', '65'),
('22', 'Guitar Amplifier', 'Amplifier', 'Blackstar', 'HT-5R', 'Used', '66'),
('23', 'Microphone', 'Microphone', 'Rode', 'NT1-A', 'New', '67'),
('24', 'Bass Amplifier', 'Amplifier', 'Ampeg', 'BA-112', 'New', '68'),
('25', 'Drum Kit', 'Drum Set', 'Pearl', 'Roadshow', 'Used', '69'),
('26', 'Keyboard', 'Synthesizer', 'Yamaha', 'PSR-E373', 'New', '70'),
('27', 'Guitar', 'Instrument', 'Fender', 'Stratocaster', 'New', '71'),
('28', 'Microphone', 'Microphone', 'Sennheiser', 'e835', 'Used', '72'),
('29', 'Combo Amplifier', 'Amplifier', 'Boss', 'Katana-50', 'New', '73'),
('30', 'Drum Kit', 'Drum Set', 'Tama', 'Imperialstar', 'New', '74'),
('31', 'Synthesizer', 'Synthesizer', 'Korg', 'MicroKorg', 'Used', '75'),
('32', 'Bass Guitar', 'Instrument', 'Squier', 'Jazz Bass', 'New', '76'),
('33', 'Microphone', 'Microphone', 'Shure', 'SM57', 'New', '77'),
('34', 'Guitar Amplifier', 'Amplifier', 'Line 6', 'Spider V', 'Used', '78'),
('35', 'Drum Kit', 'Drum Set', 'Yamaha', 'Rydeen', 'New', '79'),
('36', 'Keyboard', 'Synthesizer', 'Roland', 'FA-06', 'New', '80'),
('37', 'Guitar', 'Instrument', 'Gibson', 'Les Paul Studio', 'Used', '81'),
('38', 'Microphone', 'Microphone', 'AKG', 'C214', 'New', '82'),
('39', 'Combo Amplifier', 'Amplifier', 'Fender', 'Mustang LT25', 'New', '83'),
('40', 'Drum Kit', 'Drum Set', 'Mapex', 'Storm Series', 'New', '84');

