-- INSERTs for main.service
INSERT INTO main.service ("Id", "Name", "Price", "Type", "Requirements", "IdRehearsalPoint") VALUES 
('1', 'Synthesizer Rental', '30', 'Rental', 'None', '53'),
('2', 'Microphone Rental', '15', 'Rental', 'None', '54'),
('3', 'Combo Amplifier Rental', '40', 'Rental', 'None', '53'),
('4', 'Mixing Service', '150', 'Recording', 'DAW, audio interface, monitors', '54'),
('5', 'Mastering Service', '200', 'Recording', 'High-quality monitors, specialized software', '54'),
('6', 'Sound Recording', '180', 'Recording', 'Microphones, audio interface, soundproofing', '54'),
('7', 'Vocal Recording', '150', 'Recording', 'Microphones, pop filter, headphones', '55'),
('8', 'Guitar Rental', '20', 'Rental', 'None', '55'),
('9', 'Drum Kit Rental', '35', 'Rental', 'None', '55'),
('10', 'Piano Rental', '40', 'Rental', 'None', '56'),
('11', 'Bass Guitar Rental', '25', 'Rental', 'None', '57'),
('12', 'Live Sound Engineering', '200', 'Recording', 'PA system, microphones, mixing console', '58'),
('13', 'Sound Design', '180', 'Recording', 'Synthesizers, effects, DAW', '59'),
('14', 'Acoustic Treatment', '50', 'Rental', 'Acoustic panels, bass traps', '60'),
('15', 'Podcast Recording', '150', 'Recording', 'Microphones, soundproofing', '61'),
('16', 'Home Studio Setup', '200', 'Recording', 'Monitors, audio interface, software', '62'),
('17', 'Keyboard Rental', '30', 'Rental', 'None', '63'),
('18', 'Vocal Coaching', '100', 'Training', 'None', '64'),
('19', 'Audio Editing', '120', 'Recording', 'DAW, audio interface', '65'),
('20', 'Instrument Tuning', '25', 'Service', 'Tuning equipment', '66'),
('21', 'Live Streaming Setup', '180', 'Recording', 'Cameras, microphones, streaming software', '67'),
('22', 'Drum Tuning', '30', 'Service', 'Tuning tools', '68'),
('23', 'Guitar Amplifier Rental', '35', 'Rental', 'None', '69'),
('24', 'Mixing Console Rental', '50', 'Rental', 'None', '70'),
('25', 'Stage Lighting Rental', '60', 'Rental', 'Lighting equipment', '71'),
('26', 'Soundproofing Consultation', '80', 'Service', 'None', '72'),
('27', 'Vocal Processing', '140', 'Recording', 'DAW, plugins', '73'),
('28', 'Synthesizer Repair', '70', 'Service', 'Repair tools', '74'),
('29', 'Microphone Setup', '25', 'Service', 'None', '75'),
('30', 'Audio Mastering', '180', 'Recording', 'High-quality monitors, software', '76'),
('31', 'Live Performance Setup', '200', 'Recording', 'PA system, microphones', '77'),
('32', 'Instrument Rental Package', '50', 'Rental', 'None', '78'),
('33', 'Recording Consultation', '90', 'Service', 'None', '79'),
('34', 'Studio Monitor Rental', '40', 'Rental', 'None', '80'),
('35', 'Sound Effects Creation', '150', 'Recording', 'DAW, synthesizers', '81'),
('36', 'Vocal Booth Rental', '30', 'Rental', 'None', '82'),
('37', 'Mixing Workshop', '120', 'Training', 'DAW, monitors', '83'),
('38', 'Live Sound Training', '100', 'Training', 'PA system', '84'),
('39', 'Podcast Editing', '130', 'Recording', 'DAW, audio interface', '85'),
('40', 'Equipment Setup Service', '60', 'Service', 'None', '86');